# Who each overworld sprite is, as a recipe for mk.person(). Shades: 1 white, 2 light grey, 3 black.
cap = lambda c, b, p=1, **k: dict(t="cap", c=c, b=b, p=p, **k)
PEOPLE = {
 "red": dict(hat=cap(2, 3, 1, shadow=1), hair=3, top=2, sleeve=1, body="jacket", legs=2, pack=1),
 "red_bike": dict(bike=1, hat=cap(2, 3, 1), hair=3, top=2, sleeve=1, body="jacket", legs=3),
 "blue": dict(hair=2, style="spiky", top=3, body="emblem", mark=((0, 10), (1, 10)), legs=2),
 "oak": dict(hair=2, style="part", top=1, body="coat", shirt=3, legs=2, brows=2),
 "mom": dict(hair=3, style="bob", top=1, body="dress", apron=2, legs=1, blush=1),
 "nurse": dict(hat=dict(t="nurse", c=1, b=2), hair=2, style="bob", top=1, body="dress", apron=2, legs=1),
 "daisy": dict(hair=2, style="long", top=1, body="dress", legs=1),
 "rocket": dict(hat=cap(3, 2, 3, shadow=1), hair=3, top=3, body="emblem", legs=3, boots=1, hand=1),
 "giovanni": dict(hair=3, style="part", top=3, body="suit", tie=2, legs=3, brows=3),
 "gym_guide": dict(hair=3, style="short", shades=1, top=1, body="suit", tie=3, legs=2),
 "lorelei": dict(hair=2, style="long", glasses=1, top=3, body="dress", legs=3),
 "bruno": dict(hair=3, style="spiky", top=1, body="bare", legs=3, brows=3),
 "agatha": dict(hair=2, style="bob", top=2, body="dress", legs=2, closed=1),
 "lance": dict(hair=2, style="spiky", top=2, body="cape", cape=3, legs=2),
 "clerk": dict(hair=3, style="short", top=1, body="dress", apron=2, legs=3, hat=dict(t="band", b=1, r=2)),
 "guard": dict(hat=dict(t="peaked", c=3, b=3, band=1, shadow=1), hair=3, top=3, body="emblem", mark=((0, 10),), legs=3),
 "link_receptionist": dict(hair=3, style="bob", top=1, body="bow", shirt=2, legs=2, hat=dict(t="band", b=1, r=1)),
 "gramps": dict(hair=2, style="bald", stache=2, top=2, legs=3, closed=1),
 "granny": dict(hair=2, style="bob", top=2, body="dress", apron=1, legs=2, closed=1),
 "mr_fuji": dict(hair=2, style="bald", brows=2, beard=2, top=1, body="robe", legs=1),
 "warden": dict(hair=2, style="bald", beard=2, top=2, body="vest", legs=3),
 "captain": dict(hat=dict(t="peaked", c=1, b=3, band=3, badge=3), hair=3, top=3, body="jacket", legs=3, stache=3),
 "sailor": dict(hat=dict(t="sailor", c=1, b=3), hair=3, top=1, body="stripe", stripe=2, legs=1),
 "hiker": dict(hat=dict(t="wide", c=2, b=1, band=3), hair=3, beard=3, top=2, body="vest", legs=3, pack=1),
 "biker": dict(hat=dict(t="helmet", c=3, b=3, p=1), H=4, shades=1, eye=6, hair=3, top=3, body="jacket", legs=2),
 "scientist": dict(hair=3, style="part", glasses=1, top=1, body="coat", shirt=3, legs=3),
 "super_nerd": dict(hair=3, style="bowl", glasses=1, top=1, body="stripe", stripe=2, legs=2),
 "bike_shop_clerk": dict(hair=3, style="short", glasses=1, top=2, body="dress", apron=1, legs=3),
 "youngster": dict(hat=cap(1, 3, 2, shadow=1), hair=3, top=1, body="shorts", legs=2),
 "little_boy": dict(hair=3, style="bowl", top=1, body="stripe", stripe=3, legs=2),
 "little_girl": dict(hair=3, style="bob", top=2, body="dress", legs=2, blush=1, hat=dict(t="band", b=1, r=1)),
 "girl": dict(hair=2, style="bob", top=2, body="dress", apron=1, legs=2, hat=dict(t="band", b=3, r=2)),
 "brunette_girl": dict(hair=3, style="long", top=1, body="stripe", stripe=2, legs=2),
 "beauty": dict(hair=3, style="long", top=2, body="dress", legs=2, blush=1),
 "cooltrainer_m": dict(hair=3, style="spiky", hat=dict(t="band", b=1, r=3), top=2, body="vest", shirt=3, legs=3),
 "cooltrainer_f": dict(hair=2, style="pony", top=3, body="jacket", legs=1),
 "gambler": dict(hair=3, style="part", stache=3, top=2, body="vest", shirt=1, legs=3),
 "gentleman": dict(hat=dict(t="top", c=3, b=3, band=1), H=4, eye=7, hair=2, style="short", stache=2, top=3, body="suit", tie=2, legs=3),
 "fisher": dict(hat=dict(t="wide", c=1, b=2, band=3), hair=3, top=2, body="vest", shirt=1, legs=3),
 "fishing_guru": dict(hat=dict(t="wide", c=2, b=3, band=1), hair=2, beard=2, top=1, body="vest", shirt=2, legs=2),
 "rocker": dict(hair=3, style="spiky", shades=1, top=3, body="stripe", stripe=1, legs=2),
 "waiter": dict(hair=3, style="part", top=3, body="bow", shirt=1, legs=3),
 "cook": dict(hat=dict(t="toque", c=1, b=2), hair=3, top=1, body="dress", apron=1, legs=2, stache=3),
 "channeler": dict(hair=3, style="long", hat=dict(t="band", b=1, r=2), top=1, body="robe", sash=3, legs=1, closed=1),
 "koga": dict(hair=3, style="spiky", top=2, body="emblem", mark=((-1, 9), (0, 9), (1, 9), (2, 9), (2, 10)), legs=3, brows=3),
 "safari_zone_worker": dict(hat=dict(t="wide", c=1, b=1, band=3, shadow=1), hair=3, top=2, body="jacket", legs=1),
 "silph_president": dict(hair=2, style="bald", top=2, body="suit", tie=3, legs=2, stache=2),
 "silph_worker_m": dict(hair=3, style="part", top=2, body="suit", tie=3, legs=3),
 "silph_worker_f": dict(hair=3, style="bob", top=1, body="bow", shirt=1, legs=3),
 "middle_aged_man": dict(hair=3, style="short", stache=3, top=1, body="jacket", legs=3),
 "middle_aged_woman": dict(hair=2, style="bob", top=2, body="dress", apron=1, legs=2),
 "balding_guy": dict(hair=3, style="bald", top=2, body="stripe", stripe=1, legs=3),
 "gameboy_kid": dict(hat=cap(3, 2, 1), hair=3, top=2, legs=3, item=1, closed=0),
}
